packages:
  - name: metadata
    actions:
      - name: extract
        runtime: python:default
        web: false
        limits:
          timeout: 10000 # 10 seconds
          memory: 128 # Memory allocation (128, 256, 512, etc.)
